site-title: jacob hoover vigly
url: https://jahoo.github.io
author: Jacob Hoover Vigly
description: >
  Scientific Program Coordinator at CHI FRO, LLC.
  Formerly Postdoc at MIT, Department of Brain and Cognitive Sciences.
  PhD in Linguistics from McGill University.
bibliography: assets/bibliography/default.bib
bib-source: source.bib
nav:
  - text: home
    url: /
  - text: publications
    url: /pubs/
  - text: posts
    url: /posts/
